# Generated by Django 3.2.3 on 2021-05-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('idade_minima', models.PositiveSmallIntegerField(verbose_name='Idade mímina')),
            ],
            options={
                'verbose_name': 'Grupo atendimento',
                'verbose_name_plural': 'Grupos de atendimento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cod_munic', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código')),
                ('dsc_cidade', models.CharField(max_length=250, verbose_name='Nome')),
                ('uf', models.CharField(choices=[('RO', 'RO'), ('AC', 'AC'), ('AM', 'AM'), ('RR', 'RR'), ('PA', 'PA'), ('AP', 'AP'), ('TO', 'TO'), ('MA', 'MA'), ('PI', 'PI'), ('CE', 'CE'), ('RN', 'RN'), ('PB', 'PB'), ('PE', 'PE'), ('AL', 'AL'), ('SE', 'SE'), ('BA', 'BA'), ('MG', 'MG'), ('ES', 'ES'), ('RJ', 'RJ'), ('SP', 'SP'), ('PR', 'PR'), ('SC', 'SC'), ('RS', 'RS'), ('MS', 'MS'), ('MT', 'MT'), ('GO', 'GO'), ('DF', 'DF')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='LocalVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_latitude', models.CharField(max_length=20, verbose_name='Latitude')),
                ('vlr_longitude', models.CharField(max_length=20, verbose_name='Longitude')),
                ('cod_cnes', models.CharField(max_length=7, verbose_name='CNES')),
                ('nom_estab', models.CharField(max_length=250, verbose_name='Nome')),
                ('dsc_endereco', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('dsc_bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('dsc_telefone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefone')),
                ('dsc_estrut_fisic_ambiencia', models.CharField(max_length=250, verbose_name='Estutura física ambiencia?')),
                ('dsc_adap_defic_fisic_idosos', models.CharField(max_length=250, verbose_name='Adaptado para deficiêntes físicos ou idosos?')),
                ('dsc_equipamentos', models.CharField(max_length=250, verbose_name='Equipamentos')),
                ('dsc_medicamentos', models.CharField(max_length=250, verbose_name='Medicamentos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital023.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Local de vacinação',
                'verbose_name_plural': 'Locais de vacinação',
            },
        ),
    ]
