# Generated by Django 3.2.3 on 2021-05-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital023', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome completo')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Cidadão',
                'verbose_name_plural': 'Cidadãos',
            },
        ),
    ]
