# Generated by Django 3.2.3 on 2021-05-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital023', '0002_cidadao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(verbose_name='Para quando')),
                ('comprovante', models.CharField(max_length=250, verbose_name='Comprovante')),
                ('onde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital023.localvacinacao', verbose_name='Local de vacinação')),
                ('porque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital023.grupoatendimento', verbose_name='Grupo de atendimento')),
                ('quem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital023.cidadao', verbose_name='Cidadão')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
